### ISSUE TITLE
能支持Jvm吗？

### ISSUE THREAD

**Issue by Daimhim** [ctripcorp/mmkv-kotlin#1]
kotlin {
    jvm("desktop")
}

**Comment by qiaoyuang** [comment]
MMKV 本身不支持 JVM 桌面平台，如果 MMKV-Kotlin 要支持 JVM 桌面平台的话需要手动编写 JNI 代码，后面我们会考虑下，感谢您的建议～

**Comment by qiaoyuang** [comment]
MMKV 本身不支持 JVM 桌面平台，如果 MMKV-Kotlin 要支持 JVM 桌面平台的话需要手动编写 JNI 代码，后面我们会考虑下，感谢您的建议～
