### ISSUE TITLE
添加依赖后发布到私有cocoapods时报错

### ISSUE THREAD

**Issue by RicardoJiang** [ctripcorp/mmkv-kotlin#13]
生成xcframework没有问题，但是发布到cocoapods库时报错：
Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_MMKV", referenced from:
          objc-class-ref in xxx(result.o)
    ld: symbol(s) not found for architecture arm64

**Comment by qiaoyuang** [comment]
README 里面有一个添加 linkerOpts 的示例，你添加一下再试试看。
