### ISSUE TITLE
Building in Android Studio fails on Ubuntu

### ISSUE THREAD

**Issue by SamuelMarks** [ctripcorp/mmkv-kotlin#27]
Configuration on demand is an incubating feature.
---
> Configure project :mmkv-kotlin
w: Kotlin CocoaPods Plugin is fully supported on MacOS machines only. Gradle tasks that can not run on non-mac hosts will be skipped.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'mmkv-kotlin/mmkv-kotlin/build.gradle.kts' line: 126

* What went wrong:
Cannot get non-null property 'NEXUS_USERNAME' on project ':mmkv-kotlin' as it does not exist

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Build file 'mmkv-kotlin/mmkv-kotlin/build.gradle.kts' line: 126

* What went wrong:
Cannot get non-null property 'NEXUS_USERNAME' on project ':mmkv-kotlin' as it does not exist

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

BUILD FAILED in 1s

---
Running Android Studio (Iguana - 2023.2.1) on Ubuntu 23.10

**Comment by qiaoyuang** [comment]
You need to build it on macOS, because it needs Xcode command tool.

**Comment by SamuelMarks** [comment]
@qiaoyuang Sure but is there a flag or something so I can build it here and disable the iOS & macOS builds?

**Comment by qiaoyuang** [comment]
According your information: Try to add the 2 properties `NEXUS_USERNAME` and `NEXUS_PASSWORD` into your global `gradle.properties` file, the values are not important, if these 2 properties exist, you can pass the building.

**Comment by qiaoyuang** [comment]
@SamuelMarks Hi, did it work?

**Comment by SamuelMarks** [comment]
Ok cool I got it to build [only the Apple platforms failed] once I set these variables in the `gradle.properties`:
```ini
# MMKV
NEXUS_USERNAME=mynexususername
NEXUS_PASSWORD=mynexuspassword
SIGNING_KEY_ID=mysigningkeyid
SIGNING_KEY=mysigningkey
SIGNING_PASSWORD=mysigningpassword
```

(you might want to add this instruction to your README)

**Comment by qiaoyuang** [comment]
Okay, I will add it. Thx
